# Generated by Django 4.0.4 on 2022-06-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moodtag',
            old_name='tagtitle',
            new_name='tag_title',
        ),
    ]
