# Generated by Django 4.0.4 on 2022-06-08 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_api', '0002_rename_tagtitle_moodtag_tag_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='email',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='developer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
