# Generated by Django 4.0.4 on 2022-06-09 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_alter_developer_email_alter_developer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='user',
        ),
        migrations.AddField(
            model_name='entry',
            name='developer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='developer', to='app_api.developer'),
            preserve_default=False,
        ),
    ]
