# Generated by Django 4.0.4 on 2022-06-14 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_remove_entry_user_entry_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='moodtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.moodtag'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='techtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.techtag'),
        ),
    ]
