# Generated by Django 4.0.4 on 2022-06-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_alter_entry_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='user',
            new_name='developer',
        ),
    ]
