# Generated by Django 4.0.4 on 2022-06-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0005_alter_entry_datetime_alter_entry_moodtag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='moodtag',
        ),
        migrations.AddField(
            model_name='entry',
            name='moodtag',
            field=models.ManyToManyField(to='app_api.moodtag'),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='techtag',
        ),
        migrations.AddField(
            model_name='entry',
            name='techtag',
            field=models.ManyToManyField(to='app_api.techtag'),
        ),
    ]
