# Generated by Django 4.0.4 on 2022-06-17 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_api', '0008_alter_developer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-datetime']},
        ),
        migrations.AlterModelOptions(
            name='moodtag',
            options={'ordering': ['tag_title']},
        ),
        migrations.AlterModelOptions(
            name='techtag',
            options={'ordering': ['tech_title']},
        ),
        migrations.AlterField(
            model_name='developer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
