# Generated by Django 4.0.4 on 2022-06-18 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_api', '0009_alter_developer_options_alter_entry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
